// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cosmos/authz/v1beta1/query.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cosmos.Authz.V1Beta1 {

  /// <summary>Holder for reflection information generated from cosmos/authz/v1beta1/query.proto</summary>
  public static partial class QueryReflection {

    #region Descriptor
    /// <summary>File descriptor for cosmos/authz/v1beta1/query.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static QueryReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBjb3Ntb3MvYXV0aHovdjFiZXRhMS9xdWVyeS5wcm90bxIUY29zbW9zLmF1",
            "dGh6LnYxYmV0YTEaHGdvb2dsZS9hcGkvYW5ub3RhdGlvbnMucHJvdG8aKmNv",
            "c21vcy9iYXNlL3F1ZXJ5L3YxYmV0YTEvcGFnaW5hdGlvbi5wcm90bxogY29z",
            "bW9zL2F1dGh6L3YxYmV0YTEvYXV0aHoucHJvdG8iiAEKElF1ZXJ5R3JhbnRz",
            "UmVxdWVzdBIPCgdncmFudGVyGAEgASgJEg8KB2dyYW50ZWUYAiABKAkSFAoM",
            "bXNnX3R5cGVfdXJsGAMgASgJEjoKCnBhZ2luYXRpb24YBCABKAsyJi5jb3Nt",
            "b3MuYmFzZS5xdWVyeS52MWJldGExLlBhZ2VSZXF1ZXN0In8KE1F1ZXJ5R3Jh",
            "bnRzUmVzcG9uc2USKwoGZ3JhbnRzGAEgAygLMhsuY29zbW9zLmF1dGh6LnYx",
            "YmV0YTEuR3JhbnQSOwoKcGFnaW5hdGlvbhgCIAEoCzInLmNvc21vcy5iYXNl",
            "LnF1ZXJ5LnYxYmV0YTEuUGFnZVJlc3BvbnNlMo0BCgVRdWVyeRKDAQoGR3Jh",
            "bnRzEiguY29zbW9zLmF1dGh6LnYxYmV0YTEuUXVlcnlHcmFudHNSZXF1ZXN0",
            "GikuY29zbW9zLmF1dGh6LnYxYmV0YTEuUXVlcnlHcmFudHNSZXNwb25zZSIk",
            "gtPkkwIeEhwvY29zbW9zL2F1dGh6L3YxYmV0YTEvZ3JhbnRzQiZaJGdpdGh1",
            "Yi5jb20vY29zbW9zL2Nvc21vcy1zZGsveC9hdXRoemIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Cosmos.Base.Query.V1Beta1.PaginationReflection.Descriptor, global::Cosmos.Authz.V1Beta1.AuthzReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Cosmos.Authz.V1Beta1.QueryGrantsRequest), global::Cosmos.Authz.V1Beta1.QueryGrantsRequest.Parser, new[]{ "Granter", "Grantee", "MsgTypeUrl", "Pagination" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Cosmos.Authz.V1Beta1.QueryGrantsResponse), global::Cosmos.Authz.V1Beta1.QueryGrantsResponse.Parser, new[]{ "Grants", "Pagination" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// QueryGrantsRequest is the request type for the Query/Grants RPC method.
  /// </summary>
  public sealed partial class QueryGrantsRequest : pb::IMessage<QueryGrantsRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QueryGrantsRequest> _parser = new pb::MessageParser<QueryGrantsRequest>(() => new QueryGrantsRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QueryGrantsRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cosmos.Authz.V1Beta1.QueryReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryGrantsRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryGrantsRequest(QueryGrantsRequest other) : this() {
      granter_ = other.granter_;
      grantee_ = other.grantee_;
      msgTypeUrl_ = other.msgTypeUrl_;
      pagination_ = other.pagination_ != null ? other.pagination_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryGrantsRequest Clone() {
      return new QueryGrantsRequest(this);
    }

    /// <summary>Field number for the "granter" field.</summary>
    public const int GranterFieldNumber = 1;
    private string granter_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Granter {
      get { return granter_; }
      set {
        granter_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "grantee" field.</summary>
    public const int GranteeFieldNumber = 2;
    private string grantee_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Grantee {
      get { return grantee_; }
      set {
        grantee_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "msg_type_url" field.</summary>
    public const int MsgTypeUrlFieldNumber = 3;
    private string msgTypeUrl_ = "";
    /// <summary>
    /// Optional, msg_type_url, when set, will query only grants matching given msg type.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MsgTypeUrl {
      get { return msgTypeUrl_; }
      set {
        msgTypeUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "pagination" field.</summary>
    public const int PaginationFieldNumber = 4;
    private global::Cosmos.Base.Query.V1Beta1.PageRequest pagination_;
    /// <summary>
    /// pagination defines an pagination for the request.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cosmos.Base.Query.V1Beta1.PageRequest Pagination {
      get { return pagination_; }
      set {
        pagination_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QueryGrantsRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QueryGrantsRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Granter != other.Granter) return false;
      if (Grantee != other.Grantee) return false;
      if (MsgTypeUrl != other.MsgTypeUrl) return false;
      if (!object.Equals(Pagination, other.Pagination)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Granter.Length != 0) hash ^= Granter.GetHashCode();
      if (Grantee.Length != 0) hash ^= Grantee.GetHashCode();
      if (MsgTypeUrl.Length != 0) hash ^= MsgTypeUrl.GetHashCode();
      if (pagination_ != null) hash ^= Pagination.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Granter.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Granter);
      }
      if (Grantee.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Grantee);
      }
      if (MsgTypeUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MsgTypeUrl);
      }
      if (pagination_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Pagination);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Granter.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Granter);
      }
      if (Grantee.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Grantee);
      }
      if (MsgTypeUrl.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(MsgTypeUrl);
      }
      if (pagination_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Pagination);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Granter.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Granter);
      }
      if (Grantee.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Grantee);
      }
      if (MsgTypeUrl.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MsgTypeUrl);
      }
      if (pagination_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pagination);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QueryGrantsRequest other) {
      if (other == null) {
        return;
      }
      if (other.Granter.Length != 0) {
        Granter = other.Granter;
      }
      if (other.Grantee.Length != 0) {
        Grantee = other.Grantee;
      }
      if (other.MsgTypeUrl.Length != 0) {
        MsgTypeUrl = other.MsgTypeUrl;
      }
      if (other.pagination_ != null) {
        if (pagination_ == null) {
          Pagination = new global::Cosmos.Base.Query.V1Beta1.PageRequest();
        }
        Pagination.MergeFrom(other.Pagination);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Granter = input.ReadString();
            break;
          }
          case 18: {
            Grantee = input.ReadString();
            break;
          }
          case 26: {
            MsgTypeUrl = input.ReadString();
            break;
          }
          case 34: {
            if (pagination_ == null) {
              Pagination = new global::Cosmos.Base.Query.V1Beta1.PageRequest();
            }
            input.ReadMessage(Pagination);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Granter = input.ReadString();
            break;
          }
          case 18: {
            Grantee = input.ReadString();
            break;
          }
          case 26: {
            MsgTypeUrl = input.ReadString();
            break;
          }
          case 34: {
            if (pagination_ == null) {
              Pagination = new global::Cosmos.Base.Query.V1Beta1.PageRequest();
            }
            input.ReadMessage(Pagination);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// QueryGrantsResponse is the response type for the Query/Authorizations RPC method.
  /// </summary>
  public sealed partial class QueryGrantsResponse : pb::IMessage<QueryGrantsResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QueryGrantsResponse> _parser = new pb::MessageParser<QueryGrantsResponse>(() => new QueryGrantsResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QueryGrantsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Cosmos.Authz.V1Beta1.QueryReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryGrantsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryGrantsResponse(QueryGrantsResponse other) : this() {
      grants_ = other.grants_.Clone();
      pagination_ = other.pagination_ != null ? other.pagination_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QueryGrantsResponse Clone() {
      return new QueryGrantsResponse(this);
    }

    /// <summary>Field number for the "grants" field.</summary>
    public const int GrantsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Cosmos.Authz.V1Beta1.Grant> _repeated_grants_codec
        = pb::FieldCodec.ForMessage(10, global::Cosmos.Authz.V1Beta1.Grant.Parser);
    private readonly pbc::RepeatedField<global::Cosmos.Authz.V1Beta1.Grant> grants_ = new pbc::RepeatedField<global::Cosmos.Authz.V1Beta1.Grant>();
    /// <summary>
    /// authorizations is a list of grants granted for grantee by granter.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Cosmos.Authz.V1Beta1.Grant> Grants {
      get { return grants_; }
    }

    /// <summary>Field number for the "pagination" field.</summary>
    public const int PaginationFieldNumber = 2;
    private global::Cosmos.Base.Query.V1Beta1.PageResponse pagination_;
    /// <summary>
    /// pagination defines an pagination for the response.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cosmos.Base.Query.V1Beta1.PageResponse Pagination {
      get { return pagination_; }
      set {
        pagination_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QueryGrantsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QueryGrantsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!grants_.Equals(other.grants_)) return false;
      if (!object.Equals(Pagination, other.Pagination)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= grants_.GetHashCode();
      if (pagination_ != null) hash ^= Pagination.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      grants_.WriteTo(output, _repeated_grants_codec);
      if (pagination_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Pagination);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      grants_.WriteTo(ref output, _repeated_grants_codec);
      if (pagination_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Pagination);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += grants_.CalculateSize(_repeated_grants_codec);
      if (pagination_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pagination);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QueryGrantsResponse other) {
      if (other == null) {
        return;
      }
      grants_.Add(other.grants_);
      if (other.pagination_ != null) {
        if (pagination_ == null) {
          Pagination = new global::Cosmos.Base.Query.V1Beta1.PageResponse();
        }
        Pagination.MergeFrom(other.Pagination);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            grants_.AddEntriesFrom(input, _repeated_grants_codec);
            break;
          }
          case 18: {
            if (pagination_ == null) {
              Pagination = new global::Cosmos.Base.Query.V1Beta1.PageResponse();
            }
            input.ReadMessage(Pagination);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            grants_.AddEntriesFrom(ref input, _repeated_grants_codec);
            break;
          }
          case 18: {
            if (pagination_ == null) {
              Pagination = new global::Cosmos.Base.Query.V1Beta1.PageResponse();
            }
            input.ReadMessage(Pagination);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
