// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cosmos_proto/cosmos.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CosmosProto {

  /// <summary>Holder for reflection information generated from cosmos_proto/cosmos.proto</summary>
  public static partial class CosmosReflection {

    #region Descriptor
    /// <summary>File descriptor for cosmos_proto/cosmos.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CosmosReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chljb3Ntb3NfcHJvdG8vY29zbW9zLnByb3RvEgxjb3Ntb3NfcHJvdG8aIGdv",
            "b2dsZS9wcm90b2J1Zi9kZXNjcmlwdG9yLnByb3RvOj8KFGltcGxlbWVudHNf",
            "aW50ZXJmYWNlEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGMnW",
            "BSABKAk6OgoRYWNjZXB0c19pbnRlcmZhY2USHS5nb29nbGUucHJvdG9idWYu",
            "RmllbGRPcHRpb25zGMnWBSABKAk6LwoGc2NhbGFyEh0uZ29vZ2xlLnByb3Rv",
            "YnVmLkZpZWxkT3B0aW9ucxjK1gUgASgJQiBaHmdpdGh1Yi5jb20vY29zbW9z",
            "L2Nvc21vcy1wcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { CosmosExtensions.ImplementsInterface, CosmosExtensions.AcceptsInterface, CosmosExtensions.Scalar }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of cosmos_proto/cosmos.proto</summary>
  public static partial class CosmosExtensions {
    /// <summary>
    /// implements_interface is used to annotate interface implementations
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string> ImplementsInterface =
      new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, string>(93001, pb::FieldCodec.ForString(744010, ""));
    /// <summary>
    /// accepts_interface is used to annote fields that accept interfaces
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> AcceptsInterface =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(93001, pb::FieldCodec.ForString(744010, ""));
    /// <summary>
    /// scalar is used to define scalar types
    /// </summary>
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string> Scalar =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, string>(93002, pb::FieldCodec.ForString(744018, ""));
  }

}

#endregion Designer generated code
