// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cosmos/pools/v1beta1/pool.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Imversed.Pools.V1Beta1 {

  /// <summary>Holder for reflection information generated from cosmos/pools/v1beta1/pool.proto</summary>
  public static partial class PoolReflection {

    #region Descriptor
    /// <summary>File descriptor for cosmos/pools/v1beta1/pool.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PoolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9jb3Ntb3MvcG9vbHMvdjFiZXRhMS9wb29sLnByb3RvEhZpbXZlcnNlZC5w",
            "b29scy52MWJldGExGhljb3Ntb3NfcHJvdG8vY29zbW9zLnByb3RvGhRnb2dv",
            "cHJvdG8vZ29nby5wcm90bxoeZ29vZ2xlL3Byb3RvYnVmL2R1cmF0aW9uLnBy",
            "b3RvGh9nb29nbGUvcHJvdG9idWYvdGltZXN0YW1wLnByb3RvGh5jb3Ntb3Mv",
            "YXV0aC92MWJldGExL2F1dGgucHJvdG8aHmNvc21vcy9iYXNlL3YxYmV0YTEv",
            "Y29pbi5wcm90byKcAQoJUG9vbEFzc2V0Ej4KBXRva2VuGAEgASgLMhkuY29z",
            "bW9zLmJhc2UudjFiZXRhMS5Db2luQhTy3h8MeWFtbDoidG9rZW4iyN4fABJP",
            "CgZ3ZWlnaHQYAiABKAlCP9reHyZnaXRodWIuY29tL2Nvc21vcy9jb3Ntb3Mt",
            "c2RrL3R5cGVzLkludPLeHw15YW1sOiJ3ZWlnaHQiyN4fACKPAwoYU21vb3Ro",
            "V2VpZ2h0Q2hhbmdlUGFyYW1zEk0KCnN0YXJ0X3RpbWUYASABKAsyGi5nb29n",
            "bGUucHJvdG9idWYuVGltZXN0YW1wQh2Q3x8ByN4fAPLeHxF5YW1sOiJzdGFy",
            "dF90aW1lIhJeCghkdXJhdGlvbhgCIAEoCzIZLmdvb2dsZS5wcm90b2J1Zi5E",
            "dXJhdGlvbkIxyN4fAJjfHwHq3h8SZHVyYXRpb24sb21pdGVtcHR58t4fD3lh",
            "bWw6ImR1cmF0aW9uIhJiChJpbml0aWFsUG9vbFdlaWdodHMYAyADKAsyIS5p",
            "bXZlcnNlZC5wb29scy52MWJldGExLlBvb2xBc3NldEIj8t4fG3lhbWw6Imlu",
            "aXRpYWxfcG9vbF93ZWlnaHRzIsjeHwASYAoRdGFyZ2V0UG9vbFdlaWdodHMY",
            "BCADKAsyIS5pbXZlcnNlZC5wb29scy52MWJldGExLlBvb2xBc3NldEIi8t4f",
            "GnlhbWw6InRhcmdldF9wb29sX3dlaWdodHMiyN4fACK0AgoKUG9vbFBhcmFt",
            "cxJSCgdzd2FwRmVlGAEgASgJQkHa3h8mZ2l0aHViLmNvbS9jb3Ntb3MvY29z",
            "bW9zLXNkay90eXBlcy5EZWPy3h8PeWFtbDoic3dhcF9mZWUiyN4fABJSCgdl",
            "eGl0RmVlGAIgASgJQkHa3h8mZ2l0aHViLmNvbS9jb3Ntb3MvY29zbW9zLXNk",
            "ay90eXBlcy5EZWPy3h8PeWFtbDoiZXhpdF9mZWUiyN4fABJ+ChhzbW9vdGhX",
            "ZWlnaHRDaGFuZ2VQYXJhbXMYAyABKAsyMC5pbXZlcnNlZC5wb29scy52MWJl",
            "dGExLlNtb290aFdlaWdodENoYW5nZVBhcmFtc0Iq8t4fInlhbWw6InNtb290",
            "aF93ZWlnaHRfY2hhbmdlX3BhcmFtcyLI3h8BItkDCgRQb29sEiMKB2FkZHJl",
            "c3MYASABKAlCEvLeHw55YW1sOiJhZGRyZXNzIhIKCgJpZBgCIAEoBBJSCgpw",
            "b29sUGFyYW1zGAMgASgLMiIuaW12ZXJzZWQucG9vbHMudjFiZXRhMS5Qb29s",
            "UGFyYW1zQhry3h8SeWFtbDoicG9vbF9wYXJhbXMiyN4fABI9ChRmdXR1cmVf",
            "cG9vbF9nb3Zlcm5vchgEIAEoCUIf8t4fG3lhbWw6ImZ1dHVyZV9wb29sX2dv",
            "dmVybm9yIhJLCgt0b3RhbFNoYXJlcxgFIAEoCzIZLmNvc21vcy5iYXNlLnYx",
            "YmV0YTEuQ29pbkIb8t4fE3lhbWw6InRvdGFsX3NoYXJlcyLI3h8AElEKCnBv",
            "b2xBc3NldHMYBiADKAsyIS5pbXZlcnNlZC5wb29scy52MWJldGExLlBvb2xB",
            "c3NldEIa8t4fEnlhbWw6InBvb2xfYXNzZXRzIsjeHwASWgoLdG90YWxXZWln",
            "aHQYByABKAlCRdreHyZnaXRodWIuY29tL2Nvc21vcy9jb3Ntb3Mtc2RrL3R5",
            "cGVzLkludPLeHxN5YW1sOiJ0b3RhbF93ZWlnaHQiyN4fADoRiKAfAJigHwDK",
            "tC0FUG9vbElCLFoqZ2l0aHViLmNvbS9pbXZlcnNlZC9pbXZlcnNlZC94L3Bv",
            "b2xzL3R5cGVzYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CosmosProto.CosmosReflection.Descriptor, global::Gogoproto.GogoReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Cosmos.Auth.V1Beta1.AuthReflection.Descriptor, global::Cosmos.Base.V1Beta1.CoinReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Imversed.Pools.V1Beta1.PoolAsset), global::Imversed.Pools.V1Beta1.PoolAsset.Parser, new[]{ "Token", "Weight" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Imversed.Pools.V1Beta1.SmoothWeightChangeParams), global::Imversed.Pools.V1Beta1.SmoothWeightChangeParams.Parser, new[]{ "StartTime", "Duration", "InitialPoolWeights", "TargetPoolWeights" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Imversed.Pools.V1Beta1.PoolParams), global::Imversed.Pools.V1Beta1.PoolParams.Parser, new[]{ "SwapFee", "ExitFee", "SmoothWeightChangeParams" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Imversed.Pools.V1Beta1.Pool), global::Imversed.Pools.V1Beta1.Pool.Parser, new[]{ "Address", "Id", "PoolParams", "FuturePoolGovernor", "TotalShares", "PoolAssets", "TotalWeight" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PoolAsset : pb::IMessage<PoolAsset>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PoolAsset> _parser = new pb::MessageParser<PoolAsset>(() => new PoolAsset());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PoolAsset> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Imversed.Pools.V1Beta1.PoolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PoolAsset() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PoolAsset(PoolAsset other) : this() {
      token_ = other.token_ != null ? other.token_.Clone() : null;
      weight_ = other.weight_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PoolAsset Clone() {
      return new PoolAsset(this);
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 1;
    private global::Cosmos.Base.V1Beta1.Coin token_;
    /// <summary>
    /// Coins we are talking about,
    /// the denomination must be unique amongst all PoolAssets for this pool.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cosmos.Base.V1Beta1.Coin Token {
      get { return token_; }
      set {
        token_ = value;
      }
    }

    /// <summary>Field number for the "weight" field.</summary>
    public const int WeightFieldNumber = 2;
    private string weight_ = "";
    /// <summary>
    /// Weight that is not normalized. This weight must be less than 2^50
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Weight {
      get { return weight_; }
      set {
        weight_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PoolAsset);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PoolAsset other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Token, other.Token)) return false;
      if (Weight != other.Weight) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (token_ != null) hash ^= Token.GetHashCode();
      if (Weight.Length != 0) hash ^= Weight.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (token_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Token);
      }
      if (Weight.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Weight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (token_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Token);
      }
      if (Weight.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Weight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (token_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Token);
      }
      if (Weight.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Weight);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PoolAsset other) {
      if (other == null) {
        return;
      }
      if (other.token_ != null) {
        if (token_ == null) {
          Token = new global::Cosmos.Base.V1Beta1.Coin();
        }
        Token.MergeFrom(other.Token);
      }
      if (other.Weight.Length != 0) {
        Weight = other.Weight;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (token_ == null) {
              Token = new global::Cosmos.Base.V1Beta1.Coin();
            }
            input.ReadMessage(Token);
            break;
          }
          case 18: {
            Weight = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (token_ == null) {
              Token = new global::Cosmos.Base.V1Beta1.Coin();
            }
            input.ReadMessage(Token);
            break;
          }
          case 18: {
            Weight = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// Parameters for changing the weights in a balancer pool smoothly from
  /// a start weight and end weight over a period of time.
  /// Currently, the only smooth change supported is linear changing between
  /// the two weights, but more types may be added in the future.
  /// When these parameters are set, the weight w(t) for pool time `t` is the
  /// following:
  ///   t &lt;= start_time: w(t) = initial_pool_weights
  ///   start_time &lt; t &lt;= start_time + duration:
  ///     w(t) = initial_pool_weights + (t - start_time) *
  ///       (target_pool_weights - initial_pool_weights) / (duration)
  ///   t > start_time + duration: w(t) = target_pool_weights
  /// </summary>
  public sealed partial class SmoothWeightChangeParams : pb::IMessage<SmoothWeightChangeParams>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SmoothWeightChangeParams> _parser = new pb::MessageParser<SmoothWeightChangeParams>(() => new SmoothWeightChangeParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SmoothWeightChangeParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Imversed.Pools.V1Beta1.PoolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SmoothWeightChangeParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SmoothWeightChangeParams(SmoothWeightChangeParams other) : this() {
      startTime_ = other.startTime_ != null ? other.startTime_.Clone() : null;
      duration_ = other.duration_ != null ? other.duration_.Clone() : null;
      initialPoolWeights_ = other.initialPoolWeights_.Clone();
      targetPoolWeights_ = other.targetPoolWeights_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SmoothWeightChangeParams Clone() {
      return new SmoothWeightChangeParams(this);
    }

    /// <summary>Field number for the "start_time" field.</summary>
    public const int StartTimeFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp startTime_;
    /// <summary>
    /// The start time for beginning the weight change.
    /// If a parameter change / pool instantiation leaves this blank,
    /// it should be generated by the state_machine as the current time.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp StartTime {
      get { return startTime_; }
      set {
        startTime_ = value;
      }
    }

    /// <summary>Field number for the "duration" field.</summary>
    public const int DurationFieldNumber = 2;
    private global::Google.Protobuf.WellKnownTypes.Duration duration_;
    /// <summary>
    /// Duration for the weights to change over
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Duration Duration {
      get { return duration_; }
      set {
        duration_ = value;
      }
    }

    /// <summary>Field number for the "initialPoolWeights" field.</summary>
    public const int InitialPoolWeightsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Imversed.Pools.V1Beta1.PoolAsset> _repeated_initialPoolWeights_codec
        = pb::FieldCodec.ForMessage(26, global::Imversed.Pools.V1Beta1.PoolAsset.Parser);
    private readonly pbc::RepeatedField<global::Imversed.Pools.V1Beta1.PoolAsset> initialPoolWeights_ = new pbc::RepeatedField<global::Imversed.Pools.V1Beta1.PoolAsset>();
    /// <summary>
    /// The initial pool weights. These are copied from the pool's settings
    /// at the time of weight change instantiation.
    /// The amount PoolAsset.token.amount field is ignored if present,
    /// future type refactorings should just have a type with the denom &amp; weight
    /// here.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Imversed.Pools.V1Beta1.PoolAsset> InitialPoolWeights {
      get { return initialPoolWeights_; }
    }

    /// <summary>Field number for the "targetPoolWeights" field.</summary>
    public const int TargetPoolWeightsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Imversed.Pools.V1Beta1.PoolAsset> _repeated_targetPoolWeights_codec
        = pb::FieldCodec.ForMessage(34, global::Imversed.Pools.V1Beta1.PoolAsset.Parser);
    private readonly pbc::RepeatedField<global::Imversed.Pools.V1Beta1.PoolAsset> targetPoolWeights_ = new pbc::RepeatedField<global::Imversed.Pools.V1Beta1.PoolAsset>();
    /// <summary>
    /// The target pool weights. The pool weights will change linearly with respect
    /// to time between start_time, and start_time + duration. The amount
    /// PoolAsset.token.amount field is ignored if present, future type
    /// refactorings should just have a type with the denom &amp; weight here.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Imversed.Pools.V1Beta1.PoolAsset> TargetPoolWeights {
      get { return targetPoolWeights_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SmoothWeightChangeParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SmoothWeightChangeParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(StartTime, other.StartTime)) return false;
      if (!object.Equals(Duration, other.Duration)) return false;
      if(!initialPoolWeights_.Equals(other.initialPoolWeights_)) return false;
      if(!targetPoolWeights_.Equals(other.targetPoolWeights_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (startTime_ != null) hash ^= StartTime.GetHashCode();
      if (duration_ != null) hash ^= Duration.GetHashCode();
      hash ^= initialPoolWeights_.GetHashCode();
      hash ^= targetPoolWeights_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (startTime_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(StartTime);
      }
      if (duration_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Duration);
      }
      initialPoolWeights_.WriteTo(output, _repeated_initialPoolWeights_codec);
      targetPoolWeights_.WriteTo(output, _repeated_targetPoolWeights_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (startTime_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(StartTime);
      }
      if (duration_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Duration);
      }
      initialPoolWeights_.WriteTo(ref output, _repeated_initialPoolWeights_codec);
      targetPoolWeights_.WriteTo(ref output, _repeated_targetPoolWeights_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (startTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartTime);
      }
      if (duration_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Duration);
      }
      size += initialPoolWeights_.CalculateSize(_repeated_initialPoolWeights_codec);
      size += targetPoolWeights_.CalculateSize(_repeated_targetPoolWeights_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SmoothWeightChangeParams other) {
      if (other == null) {
        return;
      }
      if (other.startTime_ != null) {
        if (startTime_ == null) {
          StartTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        StartTime.MergeFrom(other.StartTime);
      }
      if (other.duration_ != null) {
        if (duration_ == null) {
          Duration = new global::Google.Protobuf.WellKnownTypes.Duration();
        }
        Duration.MergeFrom(other.Duration);
      }
      initialPoolWeights_.Add(other.initialPoolWeights_);
      targetPoolWeights_.Add(other.targetPoolWeights_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (startTime_ == null) {
              StartTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(StartTime);
            break;
          }
          case 18: {
            if (duration_ == null) {
              Duration = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(Duration);
            break;
          }
          case 26: {
            initialPoolWeights_.AddEntriesFrom(input, _repeated_initialPoolWeights_codec);
            break;
          }
          case 34: {
            targetPoolWeights_.AddEntriesFrom(input, _repeated_targetPoolWeights_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (startTime_ == null) {
              StartTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(StartTime);
            break;
          }
          case 18: {
            if (duration_ == null) {
              Duration = new global::Google.Protobuf.WellKnownTypes.Duration();
            }
            input.ReadMessage(Duration);
            break;
          }
          case 26: {
            initialPoolWeights_.AddEntriesFrom(ref input, _repeated_initialPoolWeights_codec);
            break;
          }
          case 34: {
            targetPoolWeights_.AddEntriesFrom(ref input, _repeated_targetPoolWeights_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// PoolParams defined the parameters that will be managed by the pool governance
  /// in the future. This params are not managed by the chain governanace.
  /// Instead they will be managed by the token holders of the pool.
  /// The pool's token holders are specified in future_pool_governor.
  /// </summary>
  public sealed partial class PoolParams : pb::IMessage<PoolParams>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PoolParams> _parser = new pb::MessageParser<PoolParams>(() => new PoolParams());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PoolParams> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Imversed.Pools.V1Beta1.PoolReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PoolParams() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PoolParams(PoolParams other) : this() {
      swapFee_ = other.swapFee_;
      exitFee_ = other.exitFee_;
      smoothWeightChangeParams_ = other.smoothWeightChangeParams_ != null ? other.smoothWeightChangeParams_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PoolParams Clone() {
      return new PoolParams(this);
    }

    /// <summary>Field number for the "swapFee" field.</summary>
    public const int SwapFeeFieldNumber = 1;
    private string swapFee_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SwapFee {
      get { return swapFee_; }
      set {
        swapFee_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "exitFee" field.</summary>
    public const int ExitFeeFieldNumber = 2;
    private string exitFee_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ExitFee {
      get { return exitFee_; }
      set {
        exitFee_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "smoothWeightChangeParams" field.</summary>
    public const int SmoothWeightChangeParamsFieldNumber = 3;
    private global::Imversed.Pools.V1Beta1.SmoothWeightChangeParams smoothWeightChangeParams_;
    /// <summary>
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Imversed.Pools.V1Beta1.SmoothWeightChangeParams SmoothWeightChangeParams {
      get { return smoothWeightChangeParams_; }
      set {
        smoothWeightChangeParams_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PoolParams);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PoolParams other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SwapFee != other.SwapFee) return false;
      if (ExitFee != other.ExitFee) return false;
      if (!object.Equals(SmoothWeightChangeParams, other.SmoothWeightChangeParams)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SwapFee.Length != 0) hash ^= SwapFee.GetHashCode();
      if (ExitFee.Length != 0) hash ^= ExitFee.GetHashCode();
      if (smoothWeightChangeParams_ != null) hash ^= SmoothWeightChangeParams.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SwapFee.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SwapFee);
      }
      if (ExitFee.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ExitFee);
      }
      if (smoothWeightChangeParams_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SmoothWeightChangeParams);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SwapFee.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(SwapFee);
      }
      if (ExitFee.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ExitFee);
      }
      if (smoothWeightChangeParams_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(SmoothWeightChangeParams);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SwapFee.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SwapFee);
      }
      if (ExitFee.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExitFee);
      }
      if (smoothWeightChangeParams_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SmoothWeightChangeParams);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PoolParams other) {
      if (other == null) {
        return;
      }
      if (other.SwapFee.Length != 0) {
        SwapFee = other.SwapFee;
      }
      if (other.ExitFee.Length != 0) {
        ExitFee = other.ExitFee;
      }
      if (other.smoothWeightChangeParams_ != null) {
        if (smoothWeightChangeParams_ == null) {
          SmoothWeightChangeParams = new global::Imversed.Pools.V1Beta1.SmoothWeightChangeParams();
        }
        SmoothWeightChangeParams.MergeFrom(other.SmoothWeightChangeParams);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            SwapFee = input.ReadString();
            break;
          }
          case 18: {
            ExitFee = input.ReadString();
            break;
          }
          case 26: {
            if (smoothWeightChangeParams_ == null) {
              SmoothWeightChangeParams = new global::Imversed.Pools.V1Beta1.SmoothWeightChangeParams();
            }
            input.ReadMessage(SmoothWeightChangeParams);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            SwapFee = input.ReadString();
            break;
          }
          case 18: {
            ExitFee = input.ReadString();
            break;
          }
          case 26: {
            if (smoothWeightChangeParams_ == null) {
              SmoothWeightChangeParams = new global::Imversed.Pools.V1Beta1.SmoothWeightChangeParams();
            }
            input.ReadMessage(SmoothWeightChangeParams);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Pool : pb::IMessage<Pool>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Pool> _parser = new pb::MessageParser<Pool>(() => new Pool());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Pool> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Imversed.Pools.V1Beta1.PoolReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Pool() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Pool(Pool other) : this() {
      address_ = other.address_;
      id_ = other.id_;
      poolParams_ = other.poolParams_ != null ? other.poolParams_.Clone() : null;
      futurePoolGovernor_ = other.futurePoolGovernor_;
      totalShares_ = other.totalShares_ != null ? other.totalShares_.Clone() : null;
      poolAssets_ = other.poolAssets_.Clone();
      totalWeight_ = other.totalWeight_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Pool Clone() {
      return new Pool(this);
    }

    /// <summary>Field number for the "address" field.</summary>
    public const int AddressFieldNumber = 1;
    private string address_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Address {
      get { return address_; }
      set {
        address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private ulong id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "poolParams" field.</summary>
    public const int PoolParamsFieldNumber = 3;
    private global::Imversed.Pools.V1Beta1.PoolParams poolParams_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Imversed.Pools.V1Beta1.PoolParams PoolParams {
      get { return poolParams_; }
      set {
        poolParams_ = value;
      }
    }

    /// <summary>Field number for the "future_pool_governor" field.</summary>
    public const int FuturePoolGovernorFieldNumber = 4;
    private string futurePoolGovernor_ = "";
    /// <summary>
    /// This string specifies who will govern the pool in the future.
    /// Valid forms of this are:
    /// {token name},{duration}
    /// {duration}
    /// where {token name} if specified is the token which determines the governor,
    /// and if not specified is the LP token for this pool.
    /// duration is a time specified as 0w,1w,2w, etc. which specifies how long the
    /// token would need to be locked up to count in governance. 0w means no
    /// lockup.
    /// TODO: Further improve these docs
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FuturePoolGovernor {
      get { return futurePoolGovernor_; }
      set {
        futurePoolGovernor_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "totalShares" field.</summary>
    public const int TotalSharesFieldNumber = 5;
    private global::Cosmos.Base.V1Beta1.Coin totalShares_;
    /// <summary>
    /// sum of all LP tokens sent out
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Cosmos.Base.V1Beta1.Coin TotalShares {
      get { return totalShares_; }
      set {
        totalShares_ = value;
      }
    }

    /// <summary>Field number for the "poolAssets" field.</summary>
    public const int PoolAssetsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Imversed.Pools.V1Beta1.PoolAsset> _repeated_poolAssets_codec
        = pb::FieldCodec.ForMessage(50, global::Imversed.Pools.V1Beta1.PoolAsset.Parser);
    private readonly pbc::RepeatedField<global::Imversed.Pools.V1Beta1.PoolAsset> poolAssets_ = new pbc::RepeatedField<global::Imversed.Pools.V1Beta1.PoolAsset>();
    /// <summary>
    /// These are assumed to be sorted by denomiation.
    /// They contain the pool asset and the information about the weight
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Imversed.Pools.V1Beta1.PoolAsset> PoolAssets {
      get { return poolAssets_; }
    }

    /// <summary>Field number for the "totalWeight" field.</summary>
    public const int TotalWeightFieldNumber = 7;
    private string totalWeight_ = "";
    /// <summary>
    /// sum of all non-normalized pool weights
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TotalWeight {
      get { return totalWeight_; }
      set {
        totalWeight_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Pool);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Pool other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Address != other.Address) return false;
      if (Id != other.Id) return false;
      if (!object.Equals(PoolParams, other.PoolParams)) return false;
      if (FuturePoolGovernor != other.FuturePoolGovernor) return false;
      if (!object.Equals(TotalShares, other.TotalShares)) return false;
      if(!poolAssets_.Equals(other.poolAssets_)) return false;
      if (TotalWeight != other.TotalWeight) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Address.Length != 0) hash ^= Address.GetHashCode();
      if (Id != 0UL) hash ^= Id.GetHashCode();
      if (poolParams_ != null) hash ^= PoolParams.GetHashCode();
      if (FuturePoolGovernor.Length != 0) hash ^= FuturePoolGovernor.GetHashCode();
      if (totalShares_ != null) hash ^= TotalShares.GetHashCode();
      hash ^= poolAssets_.GetHashCode();
      if (TotalWeight.Length != 0) hash ^= TotalWeight.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Address.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Address);
      }
      if (Id != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Id);
      }
      if (poolParams_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PoolParams);
      }
      if (FuturePoolGovernor.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FuturePoolGovernor);
      }
      if (totalShares_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(TotalShares);
      }
      poolAssets_.WriteTo(output, _repeated_poolAssets_codec);
      if (TotalWeight.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(TotalWeight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Address.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Address);
      }
      if (Id != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(Id);
      }
      if (poolParams_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PoolParams);
      }
      if (FuturePoolGovernor.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(FuturePoolGovernor);
      }
      if (totalShares_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(TotalShares);
      }
      poolAssets_.WriteTo(ref output, _repeated_poolAssets_codec);
      if (TotalWeight.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(TotalWeight);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Address.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Address);
      }
      if (Id != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
      }
      if (poolParams_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PoolParams);
      }
      if (FuturePoolGovernor.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FuturePoolGovernor);
      }
      if (totalShares_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TotalShares);
      }
      size += poolAssets_.CalculateSize(_repeated_poolAssets_codec);
      if (TotalWeight.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TotalWeight);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Pool other) {
      if (other == null) {
        return;
      }
      if (other.Address.Length != 0) {
        Address = other.Address;
      }
      if (other.Id != 0UL) {
        Id = other.Id;
      }
      if (other.poolParams_ != null) {
        if (poolParams_ == null) {
          PoolParams = new global::Imversed.Pools.V1Beta1.PoolParams();
        }
        PoolParams.MergeFrom(other.PoolParams);
      }
      if (other.FuturePoolGovernor.Length != 0) {
        FuturePoolGovernor = other.FuturePoolGovernor;
      }
      if (other.totalShares_ != null) {
        if (totalShares_ == null) {
          TotalShares = new global::Cosmos.Base.V1Beta1.Coin();
        }
        TotalShares.MergeFrom(other.TotalShares);
      }
      poolAssets_.Add(other.poolAssets_);
      if (other.TotalWeight.Length != 0) {
        TotalWeight = other.TotalWeight;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Address = input.ReadString();
            break;
          }
          case 16: {
            Id = input.ReadUInt64();
            break;
          }
          case 26: {
            if (poolParams_ == null) {
              PoolParams = new global::Imversed.Pools.V1Beta1.PoolParams();
            }
            input.ReadMessage(PoolParams);
            break;
          }
          case 34: {
            FuturePoolGovernor = input.ReadString();
            break;
          }
          case 42: {
            if (totalShares_ == null) {
              TotalShares = new global::Cosmos.Base.V1Beta1.Coin();
            }
            input.ReadMessage(TotalShares);
            break;
          }
          case 50: {
            poolAssets_.AddEntriesFrom(input, _repeated_poolAssets_codec);
            break;
          }
          case 58: {
            TotalWeight = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Address = input.ReadString();
            break;
          }
          case 16: {
            Id = input.ReadUInt64();
            break;
          }
          case 26: {
            if (poolParams_ == null) {
              PoolParams = new global::Imversed.Pools.V1Beta1.PoolParams();
            }
            input.ReadMessage(PoolParams);
            break;
          }
          case 34: {
            FuturePoolGovernor = input.ReadString();
            break;
          }
          case 42: {
            if (totalShares_ == null) {
              TotalShares = new global::Cosmos.Base.V1Beta1.Coin();
            }
            input.ReadMessage(TotalShares);
            break;
          }
          case 50: {
            poolAssets_.AddEntriesFrom(ref input, _repeated_poolAssets_codec);
            break;
          }
          case 58: {
            TotalWeight = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
