./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/confio proto-2/confio/proofs.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/gogoproto proto-2/gogoproto/gogo.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos_proto proto-2/cosmos_proto/cosmos.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/google/api proto-2/google/api/http.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/google/api proto-2/google/api/annotations.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/google/api proto-2/google/api/httpbody.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/crypto/secp256r1 proto-2/cosmos/crypto/secp256r1/keys.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/crypto/multisig proto-2/cosmos/crypto/multisig/keys.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/crypto/multisig/v1beta1 proto-2/cosmos/crypto/multisig/v1beta1/multisig.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/crypto/secp256k1 proto-2/cosmos/crypto/secp256k1/keys.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/crypto/ed25519 proto-2/cosmos/crypto/ed25519/keys.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/upgrade/v1beta1 proto-2/cosmos/upgrade/v1beta1/upgrade.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/upgrade/v1beta1 proto-2/cosmos/upgrade/v1beta1/query.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/feegrant/v1beta1 proto-2/cosmos/feegrant/v1beta1/tx.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/feegrant/v1beta1 proto-2/cosmos/feegrant/v1beta1/query.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/feegrant/v1beta1 proto-2/cosmos/feegrant/v1beta1/genesis.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/feegrant/v1beta1 proto-2/cosmos/feegrant/v1beta1/feegrant.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/mint/v1beta1 proto-2/cosmos/mint/v1beta1/query.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/mint/v1beta1 proto-2/cosmos/mint/v1beta1/genesis.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/mint/v1beta1 proto-2/cosmos/mint/v1beta1/mint.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/evidence/v1beta1 proto-2/cosmos/evidence/v1beta1/tx.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/evidence/v1beta1 proto-2/cosmos/evidence/v1beta1/evidence.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/evidence/v1beta1 proto-2/cosmos/evidence/v1beta1/query.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/evidence/v1beta1 proto-2/cosmos/evidence/v1beta1/genesis.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/nft proto-2/cosmos/nft/tx.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/nft proto-2/cosmos/nft/query.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/nft proto-2/cosmos/nft/genesis.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/nft proto-2/cosmos/nft/nft.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/auth/v1beta1 proto-2/cosmos/auth/v1beta1/query.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/auth/v1beta1 proto-2/cosmos/auth/v1beta1/genesis.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/auth/v1beta1 proto-2/cosmos/auth/v1beta1/auth.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/bank/v1beta1 proto-2/cosmos/bank/v1beta1/tx.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/bank/v1beta1 proto-2/cosmos/bank/v1beta1/bank.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/bank/v1beta1 proto-2/cosmos/bank/v1beta1/query.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/bank/v1beta1 proto-2/cosmos/bank/v1beta1/authz.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/bank/v1beta1 proto-2/cosmos/bank/v1beta1/genesis.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/capability/v1beta1 proto-2/cosmos/capability/v1beta1/capability.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/capability/v1beta1 proto-2/cosmos/capability/v1beta1/genesis.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/distribution/v1beta1 proto-2/cosmos/distribution/v1beta1/tx.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/distribution/v1beta1 proto-2/cosmos/distribution/v1beta1/distribution.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/distribution/v1beta1 proto-2/cosmos/distribution/v1beta1/query.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/distribution/v1beta1 proto-2/cosmos/distribution/v1beta1/genesis.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/crisis/v1beta1 proto-2/cosmos/crisis/v1beta1/tx.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/crisis/v1beta1 proto-2/cosmos/crisis/v1beta1/genesis.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/tx/signing/v1beta1 proto-2/cosmos/tx/signing/v1beta1/signing.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/tx/v1beta1 proto-2/cosmos/tx/v1beta1/tx.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/tx/v1beta1 proto-2/cosmos/tx/v1beta1/service.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/vesting/v1beta1 proto-2/cosmos/vesting/v1beta1/tx.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/vesting/v1beta1 proto-2/cosmos/vesting/v1beta1/vesting.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/staking/v1beta1 proto-2/cosmos/staking/v1beta1/tx.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/staking/v1beta1 proto-2/cosmos/staking/v1beta1/query.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/staking/v1beta1 proto-2/cosmos/staking/v1beta1/authz.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/staking/v1beta1 proto-2/cosmos/staking/v1beta1/genesis.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/staking/v1beta1 proto-2/cosmos/staking/v1beta1/staking.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/genutil/v1beta1 proto-2/cosmos/genutil/v1beta1/genesis.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/params/v1beta1 proto-2/cosmos/params/v1beta1/query.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/params/v1beta1 proto-2/cosmos/params/v1beta1/params.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/authz/v1beta1 proto-2/cosmos/authz/v1beta1/tx.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/authz/v1beta1 proto-2/cosmos/authz/v1beta1/query.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/authz/v1beta1 proto-2/cosmos/authz/v1beta1/event.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/authz/v1beta1 proto-2/cosmos/authz/v1beta1/authz.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/authz/v1beta1 proto-2/cosmos/authz/v1beta1/genesis.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/slashing/v1beta1 proto-2/cosmos/slashing/v1beta1/tx.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/slashing/v1beta1 proto-2/cosmos/slashing/v1beta1/slashing.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/slashing/v1beta1 proto-2/cosmos/slashing/v1beta1/query.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/slashing/v1beta1 proto-2/cosmos/slashing/v1beta1/genesis.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/base/abci/v1beta1 proto-2/cosmos/base/abci/v1beta1/abci.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/base/kv/v1beta1 proto-2/cosmos/base/kv/v1beta1/kv.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/base/snapshots/v1beta1 proto-2/cosmos/base/snapshots/v1beta1/snapshot.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/base/v1beta1 proto-2/cosmos/base/v1beta1/coin.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/base/tendermint/v1beta1 proto-2/cosmos/base/tendermint/v1beta1/query.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/base/query/v1beta1 proto-2/cosmos/base/query/v1beta1/pagination.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/base/store/v1beta1 proto-2/cosmos/base/store/v1beta1/commit_info.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/base/store/v1beta1 proto-2/cosmos/base/store/v1beta1/snapshot.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/base/store/v1beta1 proto-2/cosmos/base/store/v1beta1/listening.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/base/reflection/v1beta1 proto-2/cosmos/base/reflection/v1beta1/reflection.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/base/reflection/v2alpha1 proto-2/cosmos/base/reflection/v2alpha1/reflection.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/gov/v1beta1 proto-2/cosmos/gov/v1beta1/tx.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/gov/v1beta1 proto-2/cosmos/gov/v1beta1/gov.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/gov/v1beta1 proto-2/cosmos/gov/v1beta1/query.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/cosmos/gov/v1beta1 proto-2/cosmos/gov/v1beta1/genesis.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/tendermint/crypto proto-2/tendermint/crypto/proof.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/tendermint/crypto proto-2/tendermint/crypto/keys.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/tendermint/abci proto-2/tendermint/abci/types.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/tendermint/types proto-2/tendermint/types/evidence.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/tendermint/types proto-2/tendermint/types/types.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/tendermint/types proto-2/tendermint/types/validator.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/tendermint/types proto-2/tendermint/types/block.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/tendermint/types proto-2/tendermint/types/params.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/tendermint/libs/bits proto-2/tendermint/libs/bits/types.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/tendermint/version proto-2/tendermint/version/types.proto
./protobuf-3.19.3/src/protoc -I=./proto-2 -I=./protobuf-3.19.3/src --csharp_out=out/proto-2/tendermint/p2p proto-2/tendermint/p2p/types.proto
